<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.4.1 setup script
 * Date: Wed, 03 Jul 2013 13:12:46 -0400
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'acsa8898';

/* End of servers configuration */

$cfg['blowfish_secret'] = '51d45b5694e966.23465864';
$cfg['DefaultLang'] = 'pt_BR';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>